services:
  tailscale:
    hostname: main_server
    image: tailscale/tailscale:latest
    network_mode: "host"
    restart: no
    container_name: tailscale
    env_file: ".env"
    volumes:
      - /srv/data/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
